language: python
python:
- '3.4'
branches:
  only:
  - master
install:
- pip install ghp-import markdown lxml pelican
script:
- make publish github
env:
  global:
    secure: "Ktm2ehaqRzJlX4zrwO64gq4V6hdkK7EggVWKRYByWe51p5kPwZv4nIC9qoLLtUFHPwy9YCqpmj+hXQJP+1mn0HDckdkHpIKIyOf3xtPYqB/bSvN2+F6ufq3mwPUq+xIoy80T8U3ftSdt3B1K4Gow0XglZCKx6ydmMbAPy/TII7r4IOpSLTOjHP9Da+2HnIRrKg8UjcQusiujee1jQkQy5YUPSwr5duP7ZEZ2nFUE6XG/NdXI5efA7ekdyPKH7q5lHtHLMyKGUBTleMX/ZeBus3mc76v8kmKN3CqecHj9xPBx95X0NykRhVX4nmXWfe2Y/tQOETDZKHIA+Orb1nxZtWb8Y6cj5F1Fug5EEYTLkXRwKhowmxbPT7yPdAuZrgDdcfB/ctc+lUiXqwxr7Psp4H/kfoXhy5tqNN2p85X3nuTy9KcMeKoKbKBwPN2vIbjOFqOOtdv1wARynxdXSDXCHN/RP14ty7Ce8d1oBzSWoPm0SUrTq7sFA65fbsVPpfHJKAgoqOvvwU/GmjWTEVvmTZVnom04FBiImacoMDIAHExhSccIOL2l1eMma/zdMX+alBKrsPcwN6nl0WbP5I6D2y77A0n5EoZQYa0K3vG7L+AMvv3maJDTQtEmZWhGjLc3V4Pu2UFGPolEYvqDeEXVqysOQHpcqk7i4YgiXxnbNUc="
